# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 910b20f11617d3c50353e1f16a81e9447cacca2d431bc7d63dd400fcc9871c982580901f6493d94ed54c9d8824aaf29a1522c28e99db44df49293961beac32ef

test:
  secret_key_base: 9e1ade9e87d70e70af4e7050f06b7e2b45920137eb3a00c080762983f7157f3ad7d0fcea725c0e58e0b8507840dce64ca95b6a60804cb66b9493fc49dbec1fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
